version: '2'
services:
  db:
    image: postgres

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    restart: always

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
