# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
